### ISSUE TITLE
Emby Theater Snap cannot be started

### ISSUE THREAD

**Issue by Hans03430** [MediaBrowser/emby-theater-electron#135]
Hello, I installed the snap for Emby Theater but I see no launcher available in the app grid in Ubuntu. How can I start the application?

Emby theater is installed
![imagen](https://user-images.githubusercontent.com/56232381/218266994-91e43511-d111-45e5-9baa-8f3da7976393.png)

The app grid shows no Emby Theater launcher
![imagen](https://user-images.githubusercontent.com/56232381/218267005-007b2ce4-d9b3-4cc0-8bfc-adc38da9d2e7.png)

I tried those commands in the console but they don't work either.
![imagen](https://user-images.githubusercontent.com/56232381/218267013-493dbf56-e290-4ad8-b372-87cbb7fbda23.png)

**Comment by YinAqu** [comment]
I meet the same issue in arch linux, emby-theater version is 3.0.19.
Seems the command `emby-theater` have to be executed as `root`, though it shouldn't.
However when I executed `emby-theater`  as root, I was asked to add option `--no-sandbox`, then with `--no-sandbox` it gave me a stuck beginning screen and no any more progress.
![image](https://user-images.githubusercontent.com/16650765/218691255-e9abb657-f20f-4ad3-b1ae-f7b4fb17d019.png)
![image](https://user-images.githubusercontent.com/16650765/218691481-2c64b6c5-5492-4f4c-9290-e08c1b84b8aa.png)

**Comment by YinAqu** [comment]
I meet the same issue on arch linux, my emby-theater version is 3.0.19.
This issue is caused by a wrong privilege.
![image](https://user-images.githubusercontent.com/16650765/218695128-3bddc479-6b8d-478f-8fc6-b4f01da018e6.png)
See? The director `/usr/lib/emby-theater` has no `x` privilege for non-root users.
Try `sudo chmod +x /usr/lib/emby-theater`.

**Comment by YinAqu** [comment]
I met the same issue on arch linux, my emby-theater version is 3.0.19.
This issue is caused by a wrong privilege.
image
See? The director /usr/lib/emby-theater has no x privilege for non-root users.
Try sudo chmod +x /usr/lib/emby-theater.

**Comment by YinAqu** [comment]
I met the same issue on arch linux, emby-theater version is 3.0.19.
This issue is caused by a wrong privilege.
![image](https://user-images.githubusercontent.com/16650765/218695128-3bddc479-6b8d-478f-8fc6-b4f01da018e6.png)
See? The director `/usr/lib/emby-theater` has no `x` privilege for non-root users.
Try `sudo chmod +x /usr/lib/emby-theater`.

**Comment by YinAqu** [comment]
I met the same issue on arch linux, my emby-theater version is 3.0.19.
This issue is caused by a wrong privilege.
![image](https://user-images.githubusercontent.com/16650765/218695128-3bddc479-6b8d-478f-8fc6-b4f01da018e6.png)
See? The director `/usr/lib/emby-theater` has no `x` privilege for non-root users.
Try `sudo chmod +x /usr/lib/emby-theater`.

**Comment by alucryd** [comment]
@YinAqu Nice catch, launching with the desktop icon was working fine so I didn't notice that. Pushed an updated arch package, you'll need to uninstall the previous one first as pacman does not handle directory permission changes by itself.
```
( 6/31) upgrading emby-theater                                                                                [##################################################################] 100%
warning: directory permissions differ on /usr/lib/emby-theater/
filesystem: 700  package: 755
```

@Hans03430 We will fix that in the snap as well, and add a desktop icon shortly. Snap handles desktop icons differently than flatpak, had to do some research first.

**Comment by alucryd** [comment]
New snaps are up on the store, with desktop icon, and cli fully working.

**Comment by Hans03430** [comment]
It works now without problems :)

**Comment by LukePulverenti** [comment]
Thanks for reporting this issue.
